### ISSUE TITLE
MySQL en mode strict

### ISSUE THREAD

**Issue by Prytoegrian** [Prytoegrian/libertempo-docker#10]
Afin de blinder les échanges entre la BD et l'appli (particulièrement aux changements de version MySQL), il serait nécessaire d'avoir la configuration serveur la plus restrictive possible.
Voir la [doc](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html) pour configurer correctement le `my.cnf`.

Un truc comme ça devrait faire l'affaire :
```mysql
sql_mode = 'STRICT_ALL_TABLES,STRICT_TRANS_TABLES,NO_ENGINE_SUBSTITUTION'
```

**Comment by wouldsmina** [comment]
correction dans la structure de la BDD pour passer le mode strict : https://github.com/wouldsmina/Libertempo/pull/209
