### ISSUE TITLE
erreur sur make build

### ISSUE THREAD

**Issue by wouldsmina** [Prytoegrian/libertempo-docker#33]
j'obtiens l'erreur suivante durant  make build : 
````
Copying files from `/etc/skel' ...
Adding user `libertempo' to group `sudo' ...
Adding user libertempo to group sudo
Done.
usermod: UID '0' already exists
ERROR: Service 'libertempo' failed to build: The command '/bin/sh -c adduser --disabled-password --gecos '' libertempo &&     adduser libertempo sudo &&     echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers &&     usermod -u 0 libertempo &&     groupmod -g 0 libertempo' returned a non-zero code: 4
make: *** [Makefile:24: build] Error 1
````

**Comment by prytoegrian** [comment]
Wow. 0 ?! Je n'ai pas dû gérer un cas.

**Comment by prytoegrian** [comment]
Sudo n'est pas nécessaire, écrit simplement `make build`

**Comment by wouldsmina** [comment]
sans sudo j'ai une autre erreur : 
`ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?
`

je crois que mon docker est daubé :/

**Comment by prytoegrian** [comment]
Tente ça https://askubuntu.com/questions/477551/how-can-i-use-docker-without-sudo
J'ai fait un truc dans le genre. Après... Je vais réfléchir a une solution plus globale. Ton bug arrive quand il tente de trouver l'id d'utilisateur pour créer l'utilisateur libertempo dans le docker.

**Comment by prytoegrian** [comment]
J'ai changé la méthodo, je te laisse vérifier si ça te sied. Si c'est le cas, je te laisse fermer.
