### ISSUE TITLE
Cannot connect to the Docker daemon

### ISSUE THREAD

**Issue by wouldsmina** [Prytoegrian/libertempo-docker#4]
Sans les droits root, sur ubuntu, la création de l'image et du container retournent une erreur : 

````
$ ./build.sh 
Removing old images
Failed to remove image (libertempo): Cannot connect to the Docker daemon. Is the docker daemon running on this host?
Building dockerfile...
Cannot connect to the Docker daemon. Is the docker daemon running on this host?
````

C'est pas méchant, mais il faut le savoir.
:wink:

**Comment by Prytoegrian** [comment]
Deux questions : 
* As-tu docker lancé au démarrage ?
* As-tu fais `sudo addgroup [utilisateur] docker` ?

**Comment by wouldsmina** [comment]
> As-tu docker lancé au démarrage ?

oui

> As-tu fais sudo addgroup [utilisateur] docker ?

non :smile:

**Comment by Prytoegrian** [comment]
Tu saurais me dire si ça résout ton problème, pour que je puisse mettre une mention dans le readme ?

**Comment by Prytoegrian** [comment]
ping @wouldsmina

**Comment by wouldsmina** [comment]
oui, ça marche mieux avec l'utilisateur dans le groupe docker :)
