### ISSUE TITLE
Prérequis pour docker.io

### ISSUE THREAD

**Issue by wouldsmina** [Prytoegrian/libertempo-docker#5]
Hello,

Après une installation sur Linux Mint 17 de docker.io (depuis le dépôt officiel ubuntu), il est nécessaire d'installer les paquets `apparmor` et `cgroup-lite`. Sinon, on obtient des erreurs pas franchement claires (`Are you trying to connect to a TLS-enabled daemon without TLS` si apparmor manque et    `mountpoint for devices not found` si cgroup-lite manque). Bon à savoir, même si ce n'est pas lié au docker de Libertempo...

a+

PS : Bah dis donc, tu viens plus au soirées...? :p

**Comment by Prytoegrian** [comment]
Il est nécessaire d'installer sur **l'hôte** ces paquets tu veux dire ?

**Comment by wouldsmina** [comment]
oui, sur l'hôte.
